[project]
name = "advance-python"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "multipledispatch>=1.0.0",
    "numpy>=2.3.1",
    "requests>=2.32.4",
]
